### ISSUE TITLE
EIPsInsight meeting Aug 5

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EIPsInsight#38]
## Web pages
**Updates**
- Demo worked well, make the changes with suggested changes and add a PR

### EIP page 
- [x] Add a field or show which upgrade it belong to, only for `Standard Track - Core`
- [x] Add Status update date (Requires some time) with PR #42

### Pectra page 
- [x] Pectra (total EIPs) with #42 
- [ ] Block countdown for the upgrade [TBD]
- [x] Add a section about Pectra upgrade with #42 
- [x] Add latest Devnet specs with #42 
- [ ] Blogpost for Pectra - Devnet & other updates from ACDE/ACDC meetings.

## Toolings
**Updates**
- Demo worked well.
- PR #37 added to add tools to the main website.
- `Update`: the PR is reverted due to issues. @kaushal0398 will make another PR to update tooling section.
- Updated with #41 

**To Do**
### Reviewers
- [ ] Add title of tool `EIP Editors' Review Tracker`
  - [ ] Add a few sentences how would it work?
  - [ ] Replace "Search" with "EIP Editor's GitHub", `@` should come by default.
  - [ ] Create a hyperlink to show the data
- [ ] Add bg to chart 
  - [ ] Add footer 
  - [ ] `Total Reviews by EIP Editors (number)`
- [ ] Add a chart to show number of reviews done in years (x: years; y: numbers)
- [ ] Default chart should include all reviewers from EIP-1
   -  [ ] Chart A - Editors & numbers (Stacked Chart or Bar chart)
   -  [ ] Chart B - Years/ month & Numbers
- [ ] Both charts will use the same filter 

### PR & Issues
- [ ] Will be reviewed after the code is deployed

### GitHub PR Tracker
Open and closed PRs & Issue within a date range

### Home page
- [x] Nav bar changes  - Proposals (EIP, ERC, RIP, All), Insight Tool, More 
@viwinkumarpadala can take care of it along with other changes.With #42 
- [ ] Remove '`home` from `https://eipsinsight.com/home`

**Comment by viwinkumarpadala** [comment]
Moved the issues:
1. Block countdown for the upgrade [TBD]
2. Blogpost for Pectra - Devnet & other updates from ACDE/ACDC meetings.
3. Tools issues to the Aug 19 issues 

So, please close this to keep track of the issues using that instead.
