### ISSUE TITLE
Bugs reported at EIP Editors Review Tracker

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EIPsInsight#44]
### Bugs Reported
- [x] Capture review of all PRs merged & closed. 
  - https://github.com/ethereum/ERCs/pull/500 & https://github.com/ethereum/EIPs/pull/8608 are missing when checking it for Sam Wilson Review in Aug 2024
- [x] PRs between date should be shown even without any specified Editors name. It's throwing an error currently.

### Features requested 
- [x] Create charts with Date and number of PRs reviewed by Editors 
- [x] Single Editor chart as well as all editors (Active+Emeritus)

**Comment by EtherWorldCo** [comment]
### Aug 28, 2024

- [x] Create "Report a bug" template to create a new issue

**Comment by EtherWorldCo** [comment]
## Aug 30, 2024

- [x]  3 legends to monthly chart - Open, Closed, Merged
- [x] Create a new scheduler
- [x] Append DB
- [x] Create a document to access database from server
- [x] List the limitation/condition that PR is included in the chart
- [x] PR will be listed as expand the details.
